In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('ABC.csv',encoding='latin1')
df

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
1029,Fallen Legion: Flames of Rebellion,NaN,Role-Playing,NaN,0.00,0.00,0.00,0.00,0.00
1030,Radial G Racing Revolved,2017.0,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00
1031,The Mummy Demastered,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1032,Project Nimbus: Code Mirai,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1033,Battle Chef Brigade,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00

In [4]:
df.head()

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80

1. Identify the top 5 best-selling games globally.

In [5]:
top_selling_game = df.nlargest(5,'Global')
print('Top 5 Best-Selling Game: ')
print(top_selling_game[['Game','Global']])

Top 5 Best-Selling Game:
                        Game  Global
0         Grand Theft Auto V   19.39
1  Call of Duty: Black Ops 3   15.09
2      Red Dead Redemption 2   13.94
3         Call of Duty: WWII   13.40
4                    FIFA 18   11.80

2. Compare regional sales (North America, Europe, Japan, and Rest of the World)
for each genre to understand market preferences.

In [6]:
regional_sales = df.groupby('Genre')[['North America', 'Europe', 'Japan', 'Rest of World']].sum()
regional_sales['Total Sales'] = regional_sales.sum(axis=1)
print("Regional Sales by Genre:")
print(regional_sales)

Regional Sales by Genre:
                  North America  Europe  Japan  Rest of World  Total Sales
Genre
Action                    48.15   57.53  10.27          20.76       136.71
Action-Adventure          22.30   27.79   1.96           9.83        61.88
Adventure                  5.27    6.08   1.64           2.23        15.22
Fighting                   8.58    6.19   1.67           2.98        19.42
MMO                        1.32    1.45   0.20           0.55         3.52
Misc                       3.64    6.03   0.96           1.85        12.48
Music                      2.40    1.62   0.17           0.84         5.03
Party                      0.09    0.47   0.00           0.10         0.66
Platform                   5.48    8.92   0.67           2.77        17.84
Puzzle                     0.28    0.16   0.00           0.10         0.54
Racing                     5.86   14.77   0.76           3.81        25.20
Role-Playing              22.15   22.40   9.42           8.91        62.88
Shooter                   50.50   58.64   4.42          21.48       135.04
Simulation                 1.47    2.07   0.28           0.71         4.53
Sports                    33.31   42.81   1.83          14.90        92.85
Strategy                   0.57    0.22   0.34           0.17         1.30
Visual Novel               0.20    0.02   0.19           0.05         0.46

3. Find the publisher with the highest total global sales.

In [8]:
publisher_sales = df.groupby('Publisher')['Global'].sum()
top_publisher = publisher_sales.idxmax()
top_sales = publisher_sales.max()
print(f"The Top Publisher is {top_publisher}")
print(f"The Highest Sales is {top_sales}")

The Top Publisher is Activision
The Highest Sales is 72.44

4. Analyze the year with the highest number of game releases.

In [9]:
game_per_year = df.groupby('Year').size()
top_year = game_per_year.idxmax()
max_release = game_per_year.max()
print(f"The Heighest Number of Game release is: {top_year}")
print(f"Maximum per year game release is: {max_release}")

The Heighest Number of Game release is: 2017.0
Maximum per year game release is: 254

5. Determine the most popular genre globally based on total sales.

In [10]:
genre_sale = df.groupby('Genre')['Global'].sum()
most_popular_genre = genre_sale.idxmax()
heighest_sale = genre_sale.max()
print(f"Most Popular Genre is: {most_popular_genre}")
print(f"Heighest Sales is: {heighest_sale}")

Most Popular Genre is: Action
Heighest Sales is: 136.85

6. Identify the game with the highest sales in Japan compared to other regions.

In [ ]:
game_sales = df.groupby('Game')[]

In [11]:
df

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
1029,Fallen Legion: Flames of Rebellion,NaN,Role-Playing,NaN,0.00,0.00,0.00,0.00,0.00
1030,Radial G Racing Revolved,2017.0,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00
1031,The Mummy Demastered,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1032,Project Nimbus: Code Mirai,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1033,Battle Chef Brigade,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00